#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99
STOP=60

USE_PROCD=1

NFS_D=/var/lib/nfs
LOCK_D=/var/lib/nfs/sm

nfs_add_share() {
	local name
	local path
	local enable

	config_get name $1 name
	config_get path $1 path
	config_get enable $1 enable
[ $enable == 1 ]&&{
[ -z "$path" ] && return

echo -e "$path *(rw,no_subtree_check,all_squash,insecure,sync)" >> /etc/exports
}
}

start_service() {

  rm -rf /etc/exports
  touch /etc/exports
	config_load nfsd
	config_foreach nfs_add_share nfsshare
  /etc/init.d/portmap restart	
	grep -q /proc/fs/nfsd /proc/mounts || \
		mount -t nfsd nfsd /proc/fs/nfsd
	mkdir -p $NFS_D
	mkdir -p $LOCK_D
	touch $NFS_D/rmtab

        sysctl -w fs.nfs.nlm_tcpport=32777 fs.nfs.nlm_udpport=32777 > /dev/null
	procd_open_instance
	procd_set_param command /usr/sbin/rpc.statd -p 32778 -o 32779 -F
	procd_close_instance
	/usr/sbin/exportfs -r
	/usr/sbin/rpc.nfsd
	
	procd_open_instance
	procd_set_param command /usr/sbin/rpc.mountd -p 32780 -F
	procd_close_instance
}

stop_service() {
	rpc.nfsd 0 2> /dev/null
	/usr/sbin/exportfs -au
	grep -q /proc/fs/nfsd /proc/mounts && \
		umount /proc/fs/nfsd
}

reload() {
	/usr/sbin/exportfs -r
}

